version: "3"

services:
  database:
    image: library/postgres:14
    container_name: eventstoretestdb
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Password12!'
      POSTGRES_DB: 'marten_test'
    ports:
      - "5454:5432"